### ISSUE TITLE
ثبت نام و ورود

### ISSUE THREAD

**Issue by amirghazi87** [Ferdowsi-lang/ferdowsi-lang.github.io#1]
یک سیستم ثبت نام و ورود ریسپانسیو با پی اچ پی دارم ، مفسر آماده شد کاری کنیم کاربر کدش رو سیو کنه

**Comment by AshkanLaei** [comment]
سلام به نظرم برای فردوسی نیازی به این کار نیست ولی یه سری کار ها در ادامه دارم انجام میدم که به فردوسی هم مربوط میشه. اونجا ممکنه بشه از کدت استفاده کرد. فعلاً این ایشو رو میبندم تا بعد ببینم چی میشه
